/**:
  ros__parameters:
    minimalist_flocking_translational_velocity: 0.2
    minimalist_flocking_rotational_left_velocity: 2.0
    minimalist_flocking_rotational_right_velocity: -2.0
    minimalist_flocking_drive_timer_period: 1
    minimalist_flocking_zone1_threshold: 1.0
    minimalist_flocking_zone2_threshold: 1.0
    minimalist_flocking_zone3_threshold: 2.0
    minimalist_flocking_zone4_threshold: 4.0
    minimalist_flocking_zone2_robot_threshold: 10

    #minimalist_flocking_translational_velocity: 0.5
    #minimalist_flocking_rotational_left_velocity: 2.0
    #minimalist_flocking_rotational_right_velocity: -2.0
    #minimalist_flocking_drive_timer_period: 1
    #minimalist_flocking_zone1_threshold: 1.5
    #minimalist_flocking_zone2_threshold: 1.5
    #minimalist_flocking_zone3_threshold: 2.5
    #minimalist_flocking_zone4_threshold: 4.5
    #minimalist_flocking_zone2_robot_threshold: 7
    
    minimalist_flocking_robot_threshold: 4
    # global params
    max_range: 5.0
    min_range: 0.8
    #lidar_config: -3.1415 #0.0
